version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - test-data-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432

  migrations:
    image: flyway/flyway
    container_name: flyway
    volumes:
      - ./migrations/db:/flyway/sql
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - FLYWAY_URL=jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
      - FLYWAY_USER=${DB_USERNAME}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
      - FLYWAY_DEFAULT_SCHEMA=${DB_SCHEMA}
    command: ["migrate"]
    restart: on-failure:10
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - MODE_RUN=docker-compose
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - migrations

volumes:
  test-data-postgres-data:
#    external: true

networks:
  test-data-network:
    external: true
